### ISSUE TITLE
Starting New Project Bug

### ISSUE THREAD

**Issue by mandarin14a** [Pingendo/pingendo#1]
Launch Pingendo.
Click New Project button on pop up panel
Select Blank Page or any other
Save dialog is fixed to starting a folder on Desktop, not possible to browse to preferred location.

**Comment by Pingendo** [comment]
Maybe not so intuitive but clicking the destination folder open a choose dialog.
We should add a normal button 'choose' beside the input

![schermata 2018-09-24 alle 15 30 05](https://user-images.githubusercontent.com/8821970/45955638-b85e5600-c010-11e8-85d2-66187a488b30.png)

**Comment by mandarin14a** [comment]
Thanks, easy when you know how, Guess a button would make it obvious though.

**Comment by gseregni** [comment]
Just released v4.1.9  that add a 'choose' button...
