### ISSUE TITLE
On Mac Code Window is always Maximized

### ISSUE THREAD

**Issue by rockycastaneda** [Pingendo/pingendo#14]
I cannot minimize or shrink the size of the code window.  It always is blocking the code and project window.  I have to close the code window to go back to the Design and Project Windows.

<img width="1680" alt="screen shot 2018-10-03 at 10 54 52 pm" src="https://user-images.githubusercontent.com/11282510/46455349-7e532980-c75f-11e8-9c39-3a7e51504015.png">

**Comment by rockycastaneda** [comment]
I cannot resize the code window its covering the Design and Project Windows.  I would have to close the Code window in order for me to go back to the layout window this is very counter efficient.

**Comment by Pingendo** [comment]
@rockycastaneda can you check which version are you currently using ?

**Comment by rockycastaneda** [comment]
Version is 4.1.15

**Comment by gseregni** [comment]
@rockycastaneda are you using multiple monitors ?

**Comment by rockycastaneda** [comment]
No, im not

**Comment by rockycastaneda** [comment]
<img width="1680" alt="screen shot 2018-10-05 at 1 25 19 pm" src="https://user-images.githubusercontent.com/11282510/46558602-84055800-c8a2-11e8-838f-dcfc5dda4f68.png">

Notice that i was able to move the code window but I am unable to resize it.  Also please take note of the all black desktop all around the other windows and that is not what is on my actual desktop.

**Comment by gseregni** [comment]
Should be fixed in the latest update (4.1.16)
