### ISSUE TITLE
Update to 4.1.7 fails

### ISSUE THREAD

**Issue by mandarin14a** [Pingendo/pingendo#2]
Prompted to restar application for update, dailed. Removed application, restarted, downloaded 4.1.7 but on launch get this error message
![ping1](https://user-images.githubusercontent.com/43535274/45956860-8ac2de00-c00b-11e8-9abc-5aaa5842c9da.jpg)

**Comment by gseregni** [comment]
Sorry, just fixed in latest update (4.1.8)
Unfortunately you should re-download the app from pingendo.com
Added test to avoid happening again.. 😬
