### ISSUE TITLE
Drag Problem

### ISSUE THREAD

**Issue by npersia** [Pingendo/pingendo#26]
When I drag any component to the page, the program freezes.

I use pingendo in a Ubuntu 18.04.

Initializing the program from a terminal, i can't see any problem when its fails

**Comment by gseregni** [comment]
Any log ?

**Comment by npersia** [comment]
No, sorry. The program freezes the terminal too

**Comment by gseregni** [comment]
Can't reproduce the issue... if you wish contact me at giulio.seregni@pingendo.com to investigate further your problem
