### ISSUE TITLE
Projects window inactive or out of screen

### ISSUE THREAD

**Issue by thierry-carron** [Pingendo/pingendo#27]
When I select the Projects window button or F1 key shortcut, no project window appears. I try to look if its out of screen, but no. the Fé for src code is ok.

**Comment by thierry-carron** [comment]
even after reinstallation F1 don"t run anymore.

**Comment by gseregni** [comment]
Fix available in the next update

**Comment by gseregni** [comment]
can you see projects window under 'window' menu ?

**Comment by thierry-carron** [comment]
Nothin.
And i have the same problem than in Atom when you work on a second screen connected to the main portable/tablet pc. When you disconnect the external screen and want to open pigendo you could not see the app window which stay outside of the limit of the main screen. Even with the window keyboard shortcuts (arrow and win key combination) it is impossible to reduce, resize, or repositioning the app into the current screen view.


Thierry L. Carron

De : Giulio Seregni
Envoyé le :jeudi 8 novembre 2018 23:32
À : Pingendo/pingendo
Cc : thierry-carron; Author
Objet :Re: [Pingendo/pingendo] Projects window inactive or out of screen(#27)

can you see projects window under 'window' menu ?

**Comment by jeslenbucci** [comment]
I am having the same issue and I found a workaround. As described above, it appears to be an issue when multiple monitors are being used. 

For myself, what worked was opening the display settings (on Windows) and changing which monitor is being recognized as my main monitor. This made the projects window appear. It was also fully maximized.

**Comment by gseregni** [comment]
The problem has been fixed in the development version. A fix will be available in the next update.

**Comment by Pingendo** [comment]
Solved in 4.2.0. Just pushed.
