### ISSUE TITLE
4.1.23 Windows 10 - Application mostly unresponsive

### ISSUE THREAD

**Issue by dsghi** [Pingendo/pingendo#28]
I just installed version 4.1.23 on Windows 10 1809 build 17763.55

Most of the menu options aren't responsive, and I have some errors in the dev tools console:

```
7
42.bundle.js:8 val undefined
blank.html/ Failed to load resource: net::ERR_FILE_NOT_FOUND
2.bundle.js:8 #document #document
2.bundle.js:8 Uncaught TypeError: Cannot read property '1' of null
    at s (file:///C:/Program%20Files/Pingendo/resources/app.asar/2.bundle.js:8:587065)
    at ReadFileContext.callback (file:///C:/Program%20Files/Pingendo/resources/app.asar/2.bundle.js:8:586611)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
internal/process/next_tick.js:188 Uncaught (in promise) undefined
p-snippets.js:111 Uncaught TypeError: Cannot read property '1' of null
    at s (p-snippets.js:111)
    at dispatch (C:\Program Files\Pingendo\resources\app.asar\node_modules\jquery\dist\jquery.js:5183)
    at elemData.handle (C:\Program Files\Pingendo\resources\app.asar\node_modules\jquery\dist\jquery.js:4991)
```

**Comment by gseregni** [comment]
What you mean with 'menu options aren't responsive'... you click on application menu and nothing happens ?
Can you open pages ? 
Can you provide more details ?

**Comment by Rourkie71** [comment]
Original Poster may be having same problem as myself.

Forgive me I don't fully understand the Git hub part!! My bad.

I have installed 4.1.24 and can't open or edit page, thoough I can create a new project then can't open or edit it. LOL
I've come here as no one has aswered on Pingendo forum and this apprears to be same problem?
https://forum.pingendo.com/t/latest-pingendo-cannot-open-pages/825

Thanks in advance for reading.
Jason

**Comment by dsghi** [comment]
Not sure how I can clarify @gseregni, but nothing in the menus was working (file/edit/view/windows/help). For example, I could click file, and the menu would open, but the options which were available did nothing when clicked. This was the same for the other menus.

Unfortunately I didn't have time to troubleshoot in the last week, however I just received an update prompt and have upgraded to 4.1.25 and it appears this has resolved my problem. Thank you.

@Rourkie71 I'm not sure if this is the exact same issue you're experiencing as I see you're using Linux.  I do see a note on your forum post that it looks like they may have identified the issue. Since my issue is resolved I am going to close this, if you are continuing to have issues I would suggest opening a new one to track it.

**Comment by Rourkie71** [comment]
> 
> 
> Not sure how I can clarify @gseregni, but nothing in the menus was working (file/edit/view/windows/help). For example, I could click file, and the menu would open, but the options which were available did nothing when clicked. This was the same for the other menus.
> 
> Unfortunately I didn't have time to troubleshoot in the last week, however I just received an update prompt and have upgraded to 4.1.25 and it appears this has resolved my problem. Thank you.
> 
> @Rourkie71 I'm not sure if this is the exact same issue you're experiencing as I see you're using Linux. I do see a note on your forum post that it looks like they may have identified the issue. Since my issue is resolved I am going to close this, if you are continuing to have issues I would suggest opening a new one to track it.

Hi, I'm on Win10, I've emailed Pingendo they've replied once and said they'd sort it quickly as something was missing, but have since replied saying they have issues with some 32 bit win 10 They bought out 4.1.25 but this still hasn't sorted yet.
I'll see what they come up with, been 6 days now though. I can use the old Pingendo though :)
Thanks for replying.
Jason
