### ISSUE TITLE
Component styling bug

### ISSUE THREAD

**Issue by Bosskee** [Pingendo/pingendo#29]
Version: Pingendo 4.1.27

My project uses a bootstrap theme called Shards. Pingendo has successfully rendered components with the right CSS in previous versions, but this version doesn't seem to understand the styling.. The problem does not occur if I open a blank document.

Screencap:
[![Screenshot from Gyazo](https://gyazo.com/05295ab3ec2d9971f46728bb41e78de2/raw)](https://gyazo.com/05295ab3ec2d9971f46728bb41e78de2)

**Comment by gseregni** [comment]
Do you see other categories ok ?

**Comment by Bosskee** [comment]
> Do you see other categories ok ?

None of the categories are styled properly, they all looks like this. Is it possible to downgrade into the previous version?

**Comment by gseregni** [comment]
May i ask you to attach an example page ?

**Comment by gseregni** [comment]
You can send me to giulio.seregni@pingendo.com if you prefer to not share here

**Comment by Bosskee** [comment]
> You can send me to [giulio.seregni@pingendo.com](mailto:giulio.seregni@pingendo.com) if you prefer to not share here

I have sent you an email! :)

**Comment by gseregni** [comment]
Thank you for the mail.. the problem has been fixed and patch will be released later today

**Comment by Bosskee** [comment]
> Thank you for the mail.. the problem has been fixed and patch will be released later today

Sweet, will the patch be pushed out automatically or do I have to do something?

**Comment by Pingendo** [comment]
Solved in 4.2.0. Just pushed. just launch your app, it will update for itself.
