### ISSUE TITLE
4.1.10 on Mac opens only full screen by default

### ISSUE THREAD

**Issue by carlovettore** [Pingendo/pingendo#7]
And also the  code window and it looks like locked, on Windows it works normally.

**Comment by Pingendo** [comment]
@carlovettore this happens on OSX when setting the app in full screen. 
The fix will be available in the next release
As a workaround you can avoid to use the maximize(green) button. Instead double click on the window bar to maximaze it without going full screen

**Comment by rockycastaneda** [comment]
I posted a similar issue #14 it affected the Code window and I cannot seem to minimize or resize it.  When will 4.1.16 be out?

**Comment by gseregni** [comment]
@rockycastaneda 4.1.16 will be out this week

**Comment by rockycastaneda** [comment]
Cool

**Comment by gseregni** [comment]
Should be fixed in the latest available update (4.1.16)
