### ISSUE TITLE
Will not update

### ISSUE THREAD

**Issue by mandarin14a** [Pingendo/pingendo#9]
The Restart to update from within program fails with this:
![ping2](https://user-images.githubusercontent.com/43535274/46197004-711de100-c300-11e8-9e9f-1a7342f0d4cc.jpg)

**Comment by gseregni** [comment]
Yes unfortunately we just discovered it. Electron has introduced a big problem here. 😱
https://github.com/electron-userland/electron-builder/issues/3269

Investigating... and let you know asap.

p.s. Downloading the latest version from the website works..

**Comment by mandarin14a** [comment]
Downloaded and installed 4.1.11 but it still allows exit with Red X and no prompt to save open files.

**Comment by gseregni** [comment]
Version 4.1.13 fix the installation error on both windows and osx.
